# Generated by Django 3.1.1 on 2020-09-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPanel', '0002_auto_20200927_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
