# Generated by Django 3.1.2 on 2020-10-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userPanel', '0003_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_scrapped',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPanel.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPanel.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='solved_problems',
            field=models.ManyToManyField(through='userPanel.Submission', to='userPanel.Problem'),
        ),
    ]
