# Generated by Django 3.1.2 on 2020-10-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPanel', '0004_auto_20201027_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('SWE', 'Softwear Engineering'), ('Other', 'Other')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='solve_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Eligible', 'Eligible'), ('Blue', 'Blue'), ('Requested', 'Requested')], default='Active', max_length=100),
        ),
    ]
