# Generated by Django 3.1.2 on 2020-10-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPanel', '0005_auto_20201030_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Eligible', 'Eligible'), ('Blue', 'Blue'), ('Requested', 'Requested'), ('Request from Blue', 'Request from Blue')], default='Active', max_length=150),
        ),
    ]
