# Generated by Django 3.1.2 on 2020-11-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPanel', '0006_auto_20201030_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_submission_time',
            field=models.DateTimeField(null=True),
        ),
    ]
