# Generated by Django 3.1.4 on 2020-12-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPanel', '0007_profile_last_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
