# Generated by Django 3.2.3 on 2021-05-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPanel', '0009_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='serial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(blank=True, choices=[('Input/Output', 'Input/Output'), ('Simple Math', 'Simple Math'), ('Condition', 'Condition'), ('Loop', 'Loop'), ('Geometry', 'Geometry'), ('Array/Simple DS', 'Array/Simple DS'), ('String', 'String'), ('Ad-hoc', 'Ad-hoc')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Softwear Engineering', 'Softwear Engineering'), ('Other', 'Other')], max_length=500, null=True),
        ),
    ]
