# Generated by Django 3.2.3 on 2021-05-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPanel', '0010_auto_20210522_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Eligible', 'Eligible'), ('Blue', 'Blue'), ('Requested for Blue', 'Requested for Blue'), ('Rejected from Blue', 'Rejected from Blue')], default='Active', max_length=150),
        ),
    ]
